<?php

/**
 * Implementation of hook_perm
 *
 * Create a new permission which will decvide who can use the Create App buttons
 */
function create_app_button_perm() {
	return array('afg spawn application from centre');
}

function create_app_button_menu_alter(&$items) {
	$items['node/add/group-app-team']['type'] = MENU_CALLBACK;
}

/**
 * Add a menu item to the content creation menu for a new app
 */
function create_app_button_menu() {
  
  $items = array();
  $items['node/add/app'] = array(
    'title' => t('Application Team'),
    'description' => t('Add an App Team based at this centre'),
    'access arguments' => array('afg spawn application from centre'),
    'page callback' => 'create_app_button_create_redirect',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
 
}

function create_app_button_create_redirect() {
	
	$og = spaces_get_space();
	$type = $og->group->type;
	$id = $og->id;
  
	if ($type == 'group_centre_school') {
	  $path = 'node/add/group-app-team';
	  $qs ='edit[field_centre_ref][nid][nid]=' . $id; //Use the prepopulate module
	  drupal_goto($path, $qs);
	}
}






