<?php

function ntgmap_views_plugins() {
  return array(
    'module' => 'ntgmap',
    'style' => array(
      'ntgmap' => array(
        'title' => t('Neontribe GMap'),
        'help' => t('Displays rows as a map with pins linked to nodes.'),
        'handler' => 'ntgmap_plugin_style_gmap',
        'theme' => 'gmap_view_gmap',
        'uses row plugin' => TRUE,
        'uses grouping' => TRUE,
        'uses options' => TRUE,
        'type' => 'normal',
      ),
    ),
  );
}

