<?php
// $Id: og_user_roles_views.module,v 1.0 2010/08/08 17:34:00 destination_node Exp $

/**
 * Implementation of hook_views_api().
 */
function og_user_roles_views_views_api() {
  return array(
    'api' => 2.0,
  );
}

/**
* Access callback for use with og_user_roles_views_plugin_access.
*
* Determine if the specified user has access to a view on the basis of any of
* the requested OG user roles. If the $account argument is omitted, the current user
* is used.
*/
function og_user_roles_views_access($rids, $gid_arg, $account = NULL) {
  global $user;
  $account = isset($account) ? $account : $user;
  og_user_roles_grant_roles($account, node_load(arg($gid_arg)));

  $roles = array_keys($account->roles);
  $roles[] = $account->uid ? DRUPAL_AUTHENTICATED_RID : DRUPAL_ANONYMOUS_RID;

  return user_access('access all views', $account) || array_intersect(array_filter($rids), $roles);
}