<?php



/**
 * Add a menu item to the content creation menu for a new user
 */
function afg_manage_group_users_menu() {
  $items = array();
    
  $items['node/add/groupuser'] = array(
    'title' => t('User'),
    'description' => t('Add a new User to this Group'),
    'access arguments' => array('create users'),
    'page callback' => 'afg_manage_group_users_og_ucreate_redirect',
    'type' => MENU_NORMAL_ITEM,
  );
  
  return $items;
}

/**
 * Push a "Manage User Roles" entry into the atrium settings menu"
 */
function afg_manage_group_users_atrium_admin_links_alter($links, $space) {
    $item = menu_get_item("og/users/{$space->id}/roles");
    if ($item && $item['access']) {
        $links['roles'] = array(
          'title' => t('Manage User Roles'),
          'href' => $item['href'],
        );
      }   
}

/**
 * Adjust the display of the "subscribe" link to reflect afg_roles
 *
 * The "follow" button should show only for non-members
 *
 * Unfollow is only for 'Supporters'
 */
function afg_manage_group_users_atrium_user_links_alter(&$links, $space) {
  if ($links['subscribe']) {
    // Get RID of role 'Supporter'
    $srid = db_result(
      db_query("SELECT r.rid FROM {role} r WHERE r.name = '%s'", "Supporter")
    );
    global $user;
    $u_rids = og_user_roles_get_roles_by_group($space->id, $user->uid);
    $show_link = FALSE;    
    // If the user has _only_ the 'Supporter' role in the current group
    // let it exist
    if (count($u_rids) == 1 && in_array($srid, $u_rids)) { $show_link = TRUE; }
    // If the user has _no_ roles in the group let the subcribe link exist
    if (count($u_rids) == 0) { $show_link = TRUE; }
    // other wise remove it
    if (!$show_link) {
      unset($links['subscribe']);
    }
  }
}

/**
 * Redirect user creation to the ucreate form in this space
 *
 * Send the browser to the role manager on success
 */
function afg_manage_group_users_og_ucreate_redirect() {
    $space = !isset($space) ? spaces_get_space() : $space;
    drupal_goto(
      'og/users/' . $space->id  . '/ucreate',
      'destination=og/users/' . $space->id  . '/roles'
    );
}

function afg_manage_group_users_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'atrium_members_addform') {
    
    //Override atrium's JS behavior for this form
    drupal_add_js(
      drupal_get_path('module', 'afg_manage_group_users') .
      '/afg_atrium_members_add.js',
      'theme'
    ); 
    $space = !isset($space) ? spaces_get_space() : $space;
    unset($form['add']['#ahah']);
    $form['#redirect'] = "og/users/{$space->id}/roles";
  }
  
  
}