<?php

function block_rewrite_preprocess_block(&$vars, $hook) {
	$max_len = 28;
	if ($hook == 'block') {
		if(strlen($vars['block']->subject) > 0) {
			
			// Trim and remove any unnecessary prepended tags
			$title = trim(strip_tags($vars['block']->subject));
            $suffix = '...';
            
			$append = (strlen($title) - strlen($suffix) > $max_len) ? $suffix : '';
			$vars['block']->subject = '<h2>' . substr($title, 0, $max_len) . $append . '</h2>';
		}
	}
}